#!/usr/bin/env python3
"""Safely rebuild book.md by concatenating the FIXED chapter MD files.

This does NOT call merge_chapters.py (which would re-write chapters with
old broken structure). Instead it reads the already-fixed chapter files
in chapter_index.json order and stitches them into a single book.md.

Each chapter file is preceded by a page break (`\\newpage` for PDF builds)
and the final book gets a header + footer.
"""

import re
import json
import sys
from pathlib import Path

ROOT = Path('/Users/jianmingwang/Downloads/00_study/02_work/01_book/pcie_cxl/MindShare_PCIe_Technology_3.0_EN_VS_CN')
sys.path.insert(0, str(ROOT / 'tools'))
from merge_chapters import chapter_filename  # type: ignore


HEADER = """# 📚 MindShare PCI Express Technology 3.0 — 中英对照翻译

**PCI Express Technology — Comprehensive Guide to Generations 1.x, 2.x and 3.0**
**Authors**: Mike Jackson, Ravi Budruk · MindShare, Inc.

> 🎨 **Format**: 中英对照双语 · GitHub Flavored Markdown
> 📐 **Layout**: 50/50 双列对照表,中文灰底 (`background:#e8e8e8`)
> 🛠  **Build**: `python3 build_book.py`

---

"""


FOOTER = """

---

> 🤖 **Build**: `python3 build_book.py` (reads chapter_index.json, concatenates fixed chapter MDs)
> 📊 **Source**: `MindShare_PCI Express Technology 3.0.pdf` (1110 pages, 48 MB)
"""


def main():
    idx = json.loads((ROOT / 'chapter_index.json').read_text(encoding='utf-8'))
    chapters = idx['chapters']

    out = [HEADER]
    found, missing = [], []
    for c in chapters:
        name = chapter_filename(c['ch'], c['en'], c.get('zh', ''))
        path = ROOT / name
        if not path.exists():
            missing.append(name)
            continue
        text = path.read_text(encoding='utf-8')
        # Strip any trailing "Generated by tools/merge_chapters.py" footer from the chapter
        text = re.sub(r'\n*> 🤖 Generated by `tools/merge_chapters\.py`\s*\Z', '', text)
        # Ensure chapter ends with a clean page break
        if not text.rstrip().endswith('---'):
            text = text.rstrip() + '\n\n---\n'
        out.append(text)
        found.append(name)

    out.append(FOOTER)
    book = '\n\n\\newpage\n\n'.join(out)

    (ROOT / 'book.md').write_text(book, encoding='utf-8')

    print(f"✓ Rebuilt book.md")
    print(f"  Chapters included: {len(found)}/{len(chapters)}")
    print(f"  Output size:       {len(book.encode('utf-8')):,} bytes ({len(book.encode('utf-8'))/1024/1024:.2f} MB)")
    if missing:
        print(f"  Missing files:")
        for m in missing:
            print(f"    - {m}")


if __name__ == '__main__':
    main()
