#!/usr/bin/env python3
"""Merge translated chunks into bilingual chapter MDs.

For each chapter in chapter_index.json:
1. Read source chunks (chunks/chunk*.md) — English source
2. Read translated chunks (chunks_translated/output_chunk*.md) — Chinese translation
3. Stitch into a 2-col HTML table following the PCIe6.2_zh template:
   <table><tr><td>EN</td><td style="background:#e8e8e8">ZH</td></tr></table>
4. Save as MindShare_PCIe_chNN_<EN>_<ZH>.md

Usage:
    python3 tools/merge_chapters.py            # all chapters
    python3 tools/merge_chapters.py --ch 5     # only chapter 5
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHUNKS = ROOT / "chunks"
TRANSLATED = ROOT / "chunks_translated"
INDEX = ROOT / "chapter_index.json"


def safe_zh_filename(s: str) -> str:
    return re.sub(r"[^\w一-鿿\-]+", "_", s).strip("_")


def chapter_filename(ch: int, en: str, zh: str) -> str:
    en_slug = safe_zh_filename(en)[:50]
    zh_slug = safe_zh_filename(zh)[:30]
    return f"MindShare_PCIe_ch{ch:02d}_{en_slug}_{zh_slug}.md"


def make_section_id(ch: int, n: int) -> str:
    return f"sec-{ch}-{n}"


def render_chapter(ch_info: dict) -> str:
    """Build a single chapter MD with EN|ZH side-by-side rows."""
    ch_num = ch_info["ch"]
    en = ch_info["en"]
    zh = ch_info.get("zh", en)
    start, end = ch_info["start"], ch_info["end"]
    parts = []
    parts.append(f"# 📘 第 {ch_num} 章　{zh} (Chapter {ch_num}. {en})\n")
    parts.append("**MindShare PCI Express Technology 3.0 — Comprehensive Guide to Generations 1.x, 2.x and 3.0**\n")
    parts.append(f"> 📁 **Source chunks**: `chunks/chunk{start:04d}.md` ... `chunks/chunk{end:04d}.md`")
    parts.append(f"> 🎨 **Format**: 中英对照双语 · 中文灰底 (PCIe 6.2 Spec 模板)\n")
    parts.append("---\n")
    parts.append("## 📑 本章目录 (Table of Contents)\n")
    parts.append(f"- [{en}](#-本章目录-table-of-contents)")
    parts.append("")

    n = 0
    for chunk_n in range(start, end + 1):
        src_path = CHUNKS / f"chunk{chunk_n:04d}.md"
        out_path = TRANSLATED / f"output_chunk{chunk_n:04d}.md"
        if not src_path.exists():
            continue
        en_text = src_path.read_text(encoding='utf-8').strip()
        zh_text = ""
        if out_path.exists() and out_path.stat().st_size > 50:
            zh_text = out_path.read_text(encoding='utf-8').strip()
        if not zh_text:
            zh_text = "⚠️ TODO: 翻译未完成 / Translation pending"
        n += 1
        anchor = make_section_id(ch_num, n)
        parts.append(f'<a id="{anchor}"></a>')
        parts.append(f"## {ch_num}.{n} {en[:60]} | {zh[:30]}\n")
        parts.append("<table>")
        parts.append("<thead><tr><th width=\"50%\">🇬🇧 English</th>"
                     "<th width=\"50%\" style=\"background-color:#e8e8e8\">🇨🇳 中文</th></tr></thead>")
        parts.append("<tbody><tr>")
        parts.append(f"<td>\n\n{en_text}\n\n</td>")
        parts.append(f'<td style="background-color:#e8e8e8">\n\n{zh_text}\n\n</td>')
        parts.append("</tr></tbody></table>")
        parts.append("")
        parts.append("[⬆️ 返回目录](#-本章目录-table-of-contents)")
        parts.append("\n---\n")

    parts.append("> 🤖 Generated by `tools/merge_chapters.py`")
    return "\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ch", type=int, default=None, help="only emit this chapter number")
    args = parser.parse_args()

    idx = json.loads(INDEX.read_text(encoding='utf-8'))
    chapters = idx["chapters"]
    if args.ch is not None:
        chapters = [c for c in chapters if c["ch"] == args.ch]

    for c in chapters:
        out_name = chapter_filename(c["ch"], c["en"], c.get("zh", c["en"]))
        out_path = ROOT / out_name
        out_path.write_text(render_chapter(c), encoding='utf-8')
        print(f"  → {out_name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
